Adding AT data for the multivariate lightning algorithm
metoppv/improver_test_data pull request #44
Opened 2024-03-11 17:39 UTC by timbonin

Adding test input and KGO files needed for running the acceptance tests over the new algorithm in [IMPROVER PR #1983](https://github.com/metoppv/improver/pull/1983).

2024-04-02 11:29 UTC, gavinevans requested changes
Thanks @timbonin 👍 

I've added a couple of comments, including one that I had intended to submit previously.

2024-04-02 11:29 UTC, gavinevans commented on data/lightning-multivariate-probability-usaf2024/apcp.nc
Apologies, I meant to submit this comment previously.

> The data in these files seems highly idealised. Would it be possible to provide some inputs that are a bit more "real"? I think that would help the acceptance tests test a bit more than just what is already covered by the unit tests.

2024-04-02 11:29 UTC, gavinevans commented on data/lightning-multivariate-probability-usaf2024/apcp.nc
I notice that the point on the time (and forecast_period) coordinate for the precipitation accumulation is still set as the midpoint of the bounds. Would it be possible to update this to match our usual convention that the point for the time coordinate is defined at the end of the period? The only mention of this that I've found of this in our documentation can be seen in the `time_bnds` section in this [Time coordinate variables](https://improver.readthedocs.io/en/latest/metadata/Introduction.html#time-coordinate-variables) section.

2024-04-08 16:14 UTC, timbonin commented on data/lightning-multivariate-probability-usaf2024/apcp.nc
Got it, they certainly were idealized.  We have updated the acceptance test data to use real model inputs from a global model cut to a tropical region wherein there is variation in the conditions exercising the regression equations. We've made sure the file size of each is < 50 kB.

2024-04-08 16:15 UTC, timbonin commented on data/lightning-multivariate-probability-usaf2024/apcp.nc
We have updated this so that the time coordinate is defined as the end of the period bounds for precipitation accumulation and the lightning forecast.

2024-04-08 17:00 UTC, timbonin commented
Thanks for the review @gavinevans!  I've updated the acceptance test datasets and they should address the comments you've had.

2024-04-10 15:40 UTC, gavinevans requested changes
Thanks for the updates, @timbonin and thanks for adding some less idealised test data. 

I've added one query about the cube attributes.

For reference, I've plotted the data below: 
![Lightning_test_data](https://github.com/metoppv/improver_test_data/assets/26933341/60af786c-b98b-44da-8ee2-de9a860f4ae6)

2024-04-10 15:40 UTC, gavinevans commented on data/lightning-multivariate-probability-usaf2024/cape.nc
Just to check the metadata on these files, I ran these files through the [interpret_metadata.py](https://github.com/metoppv/improver/blob/master/improver/cli/interpret_metadata.py) CLI, and it pointed out that the `GRIB_PARAM` and `history` attributes weren't expected. Is there a reason to keep these attributes or can they be removed? To be honest, I think that there is a `history` attribute present within some of our existing files, although I don't think the `GRIB_PARAM` attribute is present anywhere else.

2024-04-10 19:52 UTC, timbonin commented on data/lightning-multivariate-probability-usaf2024/cape.nc
Got it. I removed the GRIB_PARAM and history attributes from all of the files and reran the interpret_metadata CLI, and it doesn't seem to flag any issues for me anymore.  I wasn't aware we needed to be careful with the metadata on this AT data, but rather was focused on ensuring the acceptance tests passed and otherwise looked good.

2024-04-11 06:53 UTC, gavinevans approved these changes
Thanks @timbonin 👍 . This looks fine to me now.

2024-04-15 15:27 UTC, bayliffe approved these changes

2024-04-29 13:28 UTC, merged